#-------------------------------------------------------------------------------
#.travis.yml
#-------------------------------------------------------------------------------
# Author: Alan D. Snow, 2016; Nathan Swain 2019
#-------------------------------------------------------------------------------
# System specifications for Travis CI
#-------------------------------------------------------------------------------
language: c
os:
  - linux
  - osx

env:
  - TRAVIS_PYTHON_VERSION="3.5"
  - TRAVIS_PYTHON_VERSION="3.6"
  - TRAVIS_PYTHON_VERSION="3.7"

stages:
  - name: lint
    if: branch = master
  - name: test
    if: branch = master

notifications:
  email: false

#-------------------------------------------------------------------------------
# Before installing GSSHApy
#-------------------------------------------------------------------------------
before_install:
#-------------------------------------------------------------------------------
# Add miniconda - from https://gist.github.com/dan-blanchard/7045057
#-----------------------------------------------------------------------------
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    wget -O miniconda.sh http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-MacOSX-x86_64.sh;
  fi
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $HOME/miniconda
- export PATH=$HOME/miniconda/bin:$PATH
- conda config --set always_yes yes
- conda update conda python
#-----------------------------------------------------------------------------
# Create conda environment for gsshapyorm
#-----------------------------------------------------------------------------
# build test environment
- conda env create -f conda_env.yml python=$TRAVIS_PYTHON_VERSION
# restart environment
- source activate gsshapyorm
# debugging info
- conda info
- conda list
- pip list
#-------------------------------------------------------------------------------
# Installing gsshapyorm
#--------------------------------------------------------------------------------
install:
- cd $TRAVIS_BUILD_DIR
- pip install -e .[tests]

#-------------------------------------------------------------------------------
# Testing GSSHApy
#-------------------------------------------------------------------------------
script:
- pytest --cov-report term-missing --cov=gsshapyorm

#-------------------------------------------------------------------------------
# Coveralls stats for code coverage
#-------------------------------------------------------------------------------
after_success:
  - coveralls

#-------------------------------------------------------------------------------
# Jobs
#-------------------------------------------------------------------------------
jobs:
  include:
    - stage: lint
      install:
        - pip install flake8
      script:
        - flake8
      after_success:
        - skip
